-- AlterTable
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "docType" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "field" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "expertName" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "articleAuthor" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "articleTitle" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "bookAuthor" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "bookName" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "bookChapter" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "notes" TEXT;
